#!/bin/bash
# See CONTRIBUTING.md for usage.

set -ex

TAG="docker-compose:$(git rev-parse --short HEAD)"

# By default use the Dockerfile, but can be overridden to use an alternative file
# e.g DOCKERFILE=Dockerfile.s390x script/test/default
DOCKERFILE="${DOCKERFILE:-Dockerfile}"

rm -rf coverage-html
# Create the host directory so it's owned by $USER
mkdir -p coverage-html

docker build --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy -f ${DOCKERFILE} -t "$TAG" .

GIT_VOLUME="--volume=$(pwd)/.git:/code/.git"
. script/test/all
