#!/bin/bash

set -e

. "$(dirname "${BASH_SOURCE[0]}")/utils.sh"

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
VERSION="$(git config "branch.${BRANCH}.release")" || usage

if [ -z "$(command -v jq 2> /dev/null)" ]; then
    >&2 echo "$0 requires https://stedolan.github.io/jq/"
    >&2 echo "Please install it and make sure it is available on your \$PATH."
    exit 2
fi

API=https://api.github.com/repos
REPO=docker/compose
GITHUB_REPO=git@github.com:$REPO

# Check the build status is green
sha=$(git rev-parse HEAD)
url=$API/$REPO/statuses/$sha
build_status=$(curl -s $url | jq -r '.[0].state')
if [ -n "$SKIP_BUILD_CHECK" ]; then
    echo "Skipping build status check..."
elif [[ "$build_status" != "success" ]]; then
    >&2 echo "Build status is $build_status, but it should be success."
    exit -1
fi

