#!/bin/bash
set -e


function usage() {
    >&2 cat << EOM
Print the list of github contributors for the release

Usage:

    $0 <previous release tag>
EOM
    exit 1
}

[[ -n "$1" ]] || usage
PREV_RELEASE=$1
VERSION=HEAD
URL="https://api.github.com/repos/docker/compose/compare"

contribs=$(curl -sf "$URL/$PREV_RELEASE...$VERSION" | \
    jq -r '.commits[].author.login' | \
    sort | \
    uniq -c | \
    sort -nr)

echo "Contributions by user: "
echo "$contribs"
echo
echo "$contribs" | awk '{print "@"$2","}' | xargs
