#!/bin/bash
#
# Push python packages to PyPI
#

set -ex

./script/clean

DOCKER_COMPOSE_GITSHA="$(script/build/write-git-sha)"
IMAGE_TAG="docker/compose:python-package-${DOCKER_COMPOSE_GITSHA}"

docker build -f Dockerfile.python --target publish -t "${IMAGE_TAG}" .
TMP_CONTAINER=$(docker create "${IMAGE_TAG}")
mkdir -p dist
docker cp "${TMP_CONTAINER}":/dist/. dist
docker container rm -f "${TMP_CONTAINER}"

docker container run --rm -v ${PYPIRC}:/root/.pypirc "${IMAGE_TAG}" ./script/release/publish-pypi.py --release ${TAG}

docker image rm -f "${IMAGE_TAG}"
