---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: github.com/docker/buildx
        update-types:
          - version-update:semver-minor
      - dependency-name: github.com/moby/buildkit
        update-types:
          - version-update:semver-minor
      - dependency-name: github.com/docker/cli
        update-types:
          - version-update:semver-major
      - dependency-name: github.com/docker/docker
        update-types:
          - version-update:semver-major
      - dependency-name: github.com/containerd/containerd
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: go.opentelemetry.io/*
    schedule:
      interval: daily
