
FROM    alpine:edge
RUN     apk -U add \
            curl \
            python \
            py-pip

RUN     curl https://bootstrap.pypa.io/ez_setup.py | python -

COPY    requirements.txt /code/requirements.txt
RUN     pip install -r /code/requirements.txt

ADD     dist/docker-compose-release.tar.gz /code/docker-compose
RUN     pip install --no-deps /code/docker-compose/docker-compose-*

ENTRYPOINT ["/usr/bin/docker-compose"]
