name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: ['status/0-triage', 'kind/bug']
body:
  - type: textarea
    attributes:
      label: Description
      description: |
        Briefly describe the problem you are having.

        Include both the current behavior (what you are seeing) as well as what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Compose Version
      description: |
        Paste output of `docker compose version` and `docker-compose version`.
      render: Text
    validations:
      required: false
  - type: textarea
    attributes:
      label: Docker Environment
      description: Paste output of `docker info`.
      render: Text
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
