#!/bin/bash

set -ex

if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    wget 'https://github.com/dnephin/dobi/releases/download/v0.2/dobi-linux'
    chmod +x dobi-linux
    DOCKER_API_VERSION=1.20 ./dobi-linux binary-linux

    # TODO: requires auth to push, so disable for now
    # script/build/image master
    # docker push docker/compose:master
else
    script/setup/osx
    script/build/osx
fi
