#!/bin/bash

set -ex

if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    script/build/linux
    # TODO: requires auth to push, so disable for now
    # script/build/image master
    # docker push docker/compose:master
else
    script/setup/osx
    script/build/osx
fi
