// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	CreateContainerRequest
	CreateContainerResponse
	SignalRequest
	SignalResponse
	AddProcessRequest
	User
	AddProcessResponse
	CreateCheckpointRequest
	CreateCheckpointResponse
	DeleteCheckpointRequest
	DeleteCheckpointResponse
	ListCheckpointRequest
	Checkpoint
	ListCheckpointResponse
	StateRequest
	ContainerState
	Process
	Container
	Machine
	StateResponse
	UpdateContainerRequest
	UpdateContainerResponse
	EventsRequest
	Event
	NetworkStats
	CpuUsage
	ThrottlingData
	CpuStats
	MemoryData
	MemoryStats
	BlkioStatsEntry
	BlkioStats
	HugetlbStats
	CgroupStats
	Stats
	StatsRequest
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateContainerRequest struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	BundlePath string `protobuf:"bytes,2,opt,name=bundlePath" json:"bundlePath,omitempty"`
	Stdin      string `protobuf:"bytes,3,opt,name=stdin" json:"stdin,omitempty"`
	Stdout     string `protobuf:"bytes,4,opt,name=stdout" json:"stdout,omitempty"`
	Stderr     string `protobuf:"bytes,5,opt,name=stderr" json:"stderr,omitempty"`
	Console    string `protobuf:"bytes,6,opt,name=console" json:"console,omitempty"`
	Checkpoint string `protobuf:"bytes,7,opt,name=checkpoint" json:"checkpoint,omitempty"`
}

func (m *CreateContainerRequest) Reset()                    { *m = CreateContainerRequest{} }
func (m *CreateContainerRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateContainerRequest) ProtoMessage()               {}
func (*CreateContainerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateContainerResponse struct {
}

func (m *CreateContainerResponse) Reset()                    { *m = CreateContainerResponse{} }
func (m *CreateContainerResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateContainerResponse) ProtoMessage()               {}
func (*CreateContainerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SignalRequest struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Pid    uint32 `protobuf:"varint,2,opt,name=pid" json:"pid,omitempty"`
	Signal uint32 `protobuf:"varint,3,opt,name=signal" json:"signal,omitempty"`
}

func (m *SignalRequest) Reset()                    { *m = SignalRequest{} }
func (m *SignalRequest) String() string            { return proto.CompactTextString(m) }
func (*SignalRequest) ProtoMessage()               {}
func (*SignalRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type SignalResponse struct {
}

func (m *SignalResponse) Reset()                    { *m = SignalResponse{} }
func (m *SignalResponse) String() string            { return proto.CompactTextString(m) }
func (*SignalResponse) ProtoMessage()               {}
func (*SignalResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type AddProcessRequest struct {
	Id       string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Terminal bool     `protobuf:"varint,2,opt,name=terminal" json:"terminal,omitempty"`
	User     *User    `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	Args     []string `protobuf:"bytes,4,rep,name=args" json:"args,omitempty"`
	Env      []string `protobuf:"bytes,5,rep,name=env" json:"env,omitempty"`
	Cwd      string   `protobuf:"bytes,6,opt,name=cwd" json:"cwd,omitempty"`
}

func (m *AddProcessRequest) Reset()                    { *m = AddProcessRequest{} }
func (m *AddProcessRequest) String() string            { return proto.CompactTextString(m) }
func (*AddProcessRequest) ProtoMessage()               {}
func (*AddProcessRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AddProcessRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Uid            uint32   `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Gid            uint32   `protobuf:"varint,2,opt,name=gid" json:"gid,omitempty"`
	AdditionalGids []uint32 `protobuf:"varint,3,rep,name=additionalGids" json:"additionalGids,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type AddProcessResponse struct {
	Pid uint32 `protobuf:"varint,1,opt,name=pid" json:"pid,omitempty"`
}

func (m *AddProcessResponse) Reset()                    { *m = AddProcessResponse{} }
func (m *AddProcessResponse) String() string            { return proto.CompactTextString(m) }
func (*AddProcessResponse) ProtoMessage()               {}
func (*AddProcessResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type CreateCheckpointRequest struct {
	Id         string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Checkpoint *Checkpoint `protobuf:"bytes,2,opt,name=checkpoint" json:"checkpoint,omitempty"`
}

func (m *CreateCheckpointRequest) Reset()                    { *m = CreateCheckpointRequest{} }
func (m *CreateCheckpointRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCheckpointRequest) ProtoMessage()               {}
func (*CreateCheckpointRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CreateCheckpointRequest) GetCheckpoint() *Checkpoint {
	if m != nil {
		return m.Checkpoint
	}
	return nil
}

type CreateCheckpointResponse struct {
}

func (m *CreateCheckpointResponse) Reset()                    { *m = CreateCheckpointResponse{} }
func (m *CreateCheckpointResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateCheckpointResponse) ProtoMessage()               {}
func (*CreateCheckpointResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type DeleteCheckpointRequest struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *DeleteCheckpointRequest) Reset()                    { *m = DeleteCheckpointRequest{} }
func (m *DeleteCheckpointRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteCheckpointRequest) ProtoMessage()               {}
func (*DeleteCheckpointRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type DeleteCheckpointResponse struct {
}

func (m *DeleteCheckpointResponse) Reset()                    { *m = DeleteCheckpointResponse{} }
func (m *DeleteCheckpointResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteCheckpointResponse) ProtoMessage()               {}
func (*DeleteCheckpointResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type ListCheckpointRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ListCheckpointRequest) Reset()                    { *m = ListCheckpointRequest{} }
func (m *ListCheckpointRequest) String() string            { return proto.CompactTextString(m) }
func (*ListCheckpointRequest) ProtoMessage()               {}
func (*ListCheckpointRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type Checkpoint struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Exit        bool   `protobuf:"varint,2,opt,name=exit" json:"exit,omitempty"`
	Tcp         bool   `protobuf:"varint,3,opt,name=tcp" json:"tcp,omitempty"`
	UnixSockets bool   `protobuf:"varint,4,opt,name=unixSockets" json:"unixSockets,omitempty"`
	Shell       bool   `protobuf:"varint,5,opt,name=shell" json:"shell,omitempty"`
}

func (m *Checkpoint) Reset()                    { *m = Checkpoint{} }
func (m *Checkpoint) String() string            { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()               {}
func (*Checkpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type ListCheckpointResponse struct {
	Checkpoints []*Checkpoint `protobuf:"bytes,1,rep,name=checkpoints" json:"checkpoints,omitempty"`
}

func (m *ListCheckpointResponse) Reset()                    { *m = ListCheckpointResponse{} }
func (m *ListCheckpointResponse) String() string            { return proto.CompactTextString(m) }
func (*ListCheckpointResponse) ProtoMessage()               {}
func (*ListCheckpointResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ListCheckpointResponse) GetCheckpoints() []*Checkpoint {
	if m != nil {
		return m.Checkpoints
	}
	return nil
}

type StateRequest struct {
}

func (m *StateRequest) Reset()                    { *m = StateRequest{} }
func (m *StateRequest) String() string            { return proto.CompactTextString(m) }
func (*StateRequest) ProtoMessage()               {}
func (*StateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type ContainerState struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *ContainerState) Reset()                    { *m = ContainerState{} }
func (m *ContainerState) String() string            { return proto.CompactTextString(m) }
func (*ContainerState) ProtoMessage()               {}
func (*ContainerState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type Process struct {
	Pid      uint32   `protobuf:"varint,1,opt,name=pid" json:"pid,omitempty"`
	Terminal bool     `protobuf:"varint,2,opt,name=terminal" json:"terminal,omitempty"`
	User     *User    `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	Args     []string `protobuf:"bytes,4,rep,name=args" json:"args,omitempty"`
	Env      []string `protobuf:"bytes,5,rep,name=env" json:"env,omitempty"`
	Cwd      string   `protobuf:"bytes,6,opt,name=cwd" json:"cwd,omitempty"`
}

func (m *Process) Reset()                    { *m = Process{} }
func (m *Process) String() string            { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()               {}
func (*Process) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *Process) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Container struct {
	Id         string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name       string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	BundlePath string     `protobuf:"bytes,3,opt,name=bundlePath" json:"bundlePath,omitempty"`
	Processes  []*Process `protobuf:"bytes,4,rep,name=processes" json:"processes,omitempty"`
	Status     string     `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
}

func (m *Container) Reset()                    { *m = Container{} }
func (m *Container) String() string            { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()               {}
func (*Container) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *Container) GetProcesses() []*Process {
	if m != nil {
		return m.Processes
	}
	return nil
}

// Machine is information about machine on which containerd is run
type Machine struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Cpus   uint32 `protobuf:"varint,2,opt,name=cpus" json:"cpus,omitempty"`
	Memory uint64 `protobuf:"varint,3,opt,name=memory" json:"memory,omitempty"`
}

func (m *Machine) Reset()                    { *m = Machine{} }
func (m *Machine) String() string            { return proto.CompactTextString(m) }
func (*Machine) ProtoMessage()               {}
func (*Machine) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

// StateResponse is information about containerd daemon
type StateResponse struct {
	Containers []*Container `protobuf:"bytes,1,rep,name=containers" json:"containers,omitempty"`
	Machine    *Machine     `protobuf:"bytes,2,opt,name=machine" json:"machine,omitempty"`
}

func (m *StateResponse) Reset()                    { *m = StateResponse{} }
func (m *StateResponse) String() string            { return proto.CompactTextString(m) }
func (*StateResponse) ProtoMessage()               {}
func (*StateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *StateResponse) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *StateResponse) GetMachine() *Machine {
	if m != nil {
		return m.Machine
	}
	return nil
}

type UpdateContainerRequest struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Signal uint32 `protobuf:"varint,2,opt,name=signal" json:"signal,omitempty"`
	Status string `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *UpdateContainerRequest) Reset()                    { *m = UpdateContainerRequest{} }
func (m *UpdateContainerRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateContainerRequest) ProtoMessage()               {}
func (*UpdateContainerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type UpdateContainerResponse struct {
}

func (m *UpdateContainerResponse) Reset()                    { *m = UpdateContainerResponse{} }
func (m *UpdateContainerResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateContainerResponse) ProtoMessage()               {}
func (*UpdateContainerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type EventsRequest struct {
}

func (m *EventsRequest) Reset()                    { *m = EventsRequest{} }
func (m *EventsRequest) String() string            { return proto.CompactTextString(m) }
func (*EventsRequest) ProtoMessage()               {}
func (*EventsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

type Event struct {
	Type       string       `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Id         string       `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Status     uint32       `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	BundlePath string       `protobuf:"bytes,4,opt,name=bundlePath" json:"bundlePath,omitempty"`
	Pid        uint32       `protobuf:"varint,5,opt,name=pid" json:"pid,omitempty"`
	Signal     uint32       `protobuf:"varint,7,opt,name=signal" json:"signal,omitempty"`
	Process    *Process     `protobuf:"bytes,8,opt,name=process" json:"process,omitempty"`
	Containers []*Container `protobuf:"bytes,9,rep,name=containers" json:"containers,omitempty"`
	Checkpoint *Checkpoint  `protobuf:"bytes,10,opt,name=checkpoint" json:"checkpoint,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *Event) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *Event) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Event) GetCheckpoint() *Checkpoint {
	if m != nil {
		return m.Checkpoint
	}
	return nil
}

type NetworkStats struct {
	Name       string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	RxBytes    uint64 `protobuf:"varint,2,opt,name=rx_bytes" json:"rx_bytes,omitempty"`
	Rx_Packets uint64 `protobuf:"varint,3,opt,name=rx_Packets" json:"rx_Packets,omitempty"`
	RxErrors   uint64 `protobuf:"varint,4,opt,name=Rx_errors" json:"Rx_errors,omitempty"`
	RxDropped  uint64 `protobuf:"varint,5,opt,name=Rx_dropped" json:"Rx_dropped,omitempty"`
	TxBytes    uint64 `protobuf:"varint,6,opt,name=Tx_bytes" json:"Tx_bytes,omitempty"`
	TxPackets  uint64 `protobuf:"varint,7,opt,name=Tx_packets" json:"Tx_packets,omitempty"`
	TxErrors   uint64 `protobuf:"varint,8,opt,name=Tx_errors" json:"Tx_errors,omitempty"`
	TxDropped  uint64 `protobuf:"varint,9,opt,name=Tx_dropped" json:"Tx_dropped,omitempty"`
}

func (m *NetworkStats) Reset()                    { *m = NetworkStats{} }
func (m *NetworkStats) String() string            { return proto.CompactTextString(m) }
func (*NetworkStats) ProtoMessage()               {}
func (*NetworkStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

type CpuUsage struct {
	TotalUsage        uint64   `protobuf:"varint,1,opt,name=total_usage" json:"total_usage,omitempty"`
	PercpuUsage       []uint64 `protobuf:"varint,2,rep,name=percpu_usage" json:"percpu_usage,omitempty"`
	UsageInKernelmode uint64   `protobuf:"varint,3,opt,name=usage_in_kernelmode" json:"usage_in_kernelmode,omitempty"`
	UsageInUsermode   uint64   `protobuf:"varint,4,opt,name=usage_in_usermode" json:"usage_in_usermode,omitempty"`
}

func (m *CpuUsage) Reset()                    { *m = CpuUsage{} }
func (m *CpuUsage) String() string            { return proto.CompactTextString(m) }
func (*CpuUsage) ProtoMessage()               {}
func (*CpuUsage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

type ThrottlingData struct {
	Periods          uint64 `protobuf:"varint,1,opt,name=periods" json:"periods,omitempty"`
	ThrottledPeriods uint64 `protobuf:"varint,2,opt,name=throttled_periods" json:"throttled_periods,omitempty"`
	ThrottledTime    uint64 `protobuf:"varint,3,opt,name=throttled_time" json:"throttled_time,omitempty"`
}

func (m *ThrottlingData) Reset()                    { *m = ThrottlingData{} }
func (m *ThrottlingData) String() string            { return proto.CompactTextString(m) }
func (*ThrottlingData) ProtoMessage()               {}
func (*ThrottlingData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

type CpuStats struct {
	CpuUsage       *CpuUsage       `protobuf:"bytes,1,opt,name=cpu_usage" json:"cpu_usage,omitempty"`
	ThrottlingData *ThrottlingData `protobuf:"bytes,2,opt,name=throttling_data" json:"throttling_data,omitempty"`
}

func (m *CpuStats) Reset()                    { *m = CpuStats{} }
func (m *CpuStats) String() string            { return proto.CompactTextString(m) }
func (*CpuStats) ProtoMessage()               {}
func (*CpuStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *CpuStats) GetCpuUsage() *CpuUsage {
	if m != nil {
		return m.CpuUsage
	}
	return nil
}

func (m *CpuStats) GetThrottlingData() *ThrottlingData {
	if m != nil {
		return m.ThrottlingData
	}
	return nil
}

type MemoryData struct {
	Usage    uint64 `protobuf:"varint,1,opt,name=usage" json:"usage,omitempty"`
	MaxUsage uint64 `protobuf:"varint,2,opt,name=max_usage" json:"max_usage,omitempty"`
	Failcnt  uint64 `protobuf:"varint,3,opt,name=failcnt" json:"failcnt,omitempty"`
}

func (m *MemoryData) Reset()                    { *m = MemoryData{} }
func (m *MemoryData) String() string            { return proto.CompactTextString(m) }
func (*MemoryData) ProtoMessage()               {}
func (*MemoryData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

type MemoryStats struct {
	Cache       uint64            `protobuf:"varint,1,opt,name=cache" json:"cache,omitempty"`
	Usage       *MemoryData       `protobuf:"bytes,2,opt,name=usage" json:"usage,omitempty"`
	SwapUsage   *MemoryData       `protobuf:"bytes,3,opt,name=swap_usage" json:"swap_usage,omitempty"`
	KernelUsage *MemoryData       `protobuf:"bytes,4,opt,name=kernel_usage" json:"kernel_usage,omitempty"`
	Stats       map[string]uint64 `protobuf:"bytes,5,rep,name=stats" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *MemoryStats) Reset()                    { *m = MemoryStats{} }
func (m *MemoryStats) String() string            { return proto.CompactTextString(m) }
func (*MemoryStats) ProtoMessage()               {}
func (*MemoryStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *MemoryStats) GetUsage() *MemoryData {
	if m != nil {
		return m.Usage
	}
	return nil
}

func (m *MemoryStats) GetSwapUsage() *MemoryData {
	if m != nil {
		return m.SwapUsage
	}
	return nil
}

func (m *MemoryStats) GetKernelUsage() *MemoryData {
	if m != nil {
		return m.KernelUsage
	}
	return nil
}

func (m *MemoryStats) GetStats() map[string]uint64 {
	if m != nil {
		return m.Stats
	}
	return nil
}

type BlkioStatsEntry struct {
	Major uint64 `protobuf:"varint,1,opt,name=major" json:"major,omitempty"`
	Minor uint64 `protobuf:"varint,2,opt,name=minor" json:"minor,omitempty"`
	Op    string `protobuf:"bytes,3,opt,name=op" json:"op,omitempty"`
	Value uint64 `protobuf:"varint,4,opt,name=value" json:"value,omitempty"`
}

func (m *BlkioStatsEntry) Reset()                    { *m = BlkioStatsEntry{} }
func (m *BlkioStatsEntry) String() string            { return proto.CompactTextString(m) }
func (*BlkioStatsEntry) ProtoMessage()               {}
func (*BlkioStatsEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

type BlkioStats struct {
	IoServiceBytesRecursive []*BlkioStatsEntry `protobuf:"bytes,1,rep,name=io_service_bytes_recursive" json:"io_service_bytes_recursive,omitempty"`
	IoServicedRecursive     []*BlkioStatsEntry `protobuf:"bytes,2,rep,name=io_serviced_recursive" json:"io_serviced_recursive,omitempty"`
	IoQueuedRecursive       []*BlkioStatsEntry `protobuf:"bytes,3,rep,name=io_queued_recursive" json:"io_queued_recursive,omitempty"`
	IoServiceTimeRecursive  []*BlkioStatsEntry `protobuf:"bytes,4,rep,name=io_service_time_recursive" json:"io_service_time_recursive,omitempty"`
	IoWaitTimeRecursive     []*BlkioStatsEntry `protobuf:"bytes,5,rep,name=io_wait_time_recursive" json:"io_wait_time_recursive,omitempty"`
	IoMergedRecursive       []*BlkioStatsEntry `protobuf:"bytes,6,rep,name=io_merged_recursive" json:"io_merged_recursive,omitempty"`
	IoTimeRecursive         []*BlkioStatsEntry `protobuf:"bytes,7,rep,name=io_time_recursive" json:"io_time_recursive,omitempty"`
	SectorsRecursive        []*BlkioStatsEntry `protobuf:"bytes,8,rep,name=sectors_recursive" json:"sectors_recursive,omitempty"`
}

func (m *BlkioStats) Reset()                    { *m = BlkioStats{} }
func (m *BlkioStats) String() string            { return proto.CompactTextString(m) }
func (*BlkioStats) ProtoMessage()               {}
func (*BlkioStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *BlkioStats) GetIoServiceBytesRecursive() []*BlkioStatsEntry {
	if m != nil {
		return m.IoServiceBytesRecursive
	}
	return nil
}

func (m *BlkioStats) GetIoServicedRecursive() []*BlkioStatsEntry {
	if m != nil {
		return m.IoServicedRecursive
	}
	return nil
}

func (m *BlkioStats) GetIoQueuedRecursive() []*BlkioStatsEntry {
	if m != nil {
		return m.IoQueuedRecursive
	}
	return nil
}

func (m *BlkioStats) GetIoServiceTimeRecursive() []*BlkioStatsEntry {
	if m != nil {
		return m.IoServiceTimeRecursive
	}
	return nil
}

func (m *BlkioStats) GetIoWaitTimeRecursive() []*BlkioStatsEntry {
	if m != nil {
		return m.IoWaitTimeRecursive
	}
	return nil
}

func (m *BlkioStats) GetIoMergedRecursive() []*BlkioStatsEntry {
	if m != nil {
		return m.IoMergedRecursive
	}
	return nil
}

func (m *BlkioStats) GetIoTimeRecursive() []*BlkioStatsEntry {
	if m != nil {
		return m.IoTimeRecursive
	}
	return nil
}

func (m *BlkioStats) GetSectorsRecursive() []*BlkioStatsEntry {
	if m != nil {
		return m.SectorsRecursive
	}
	return nil
}

type HugetlbStats struct {
	Usage    uint64 `protobuf:"varint,1,opt,name=usage" json:"usage,omitempty"`
	MaxUsage uint64 `protobuf:"varint,2,opt,name=max_usage" json:"max_usage,omitempty"`
	Failcnt  uint64 `protobuf:"varint,3,opt,name=failcnt" json:"failcnt,omitempty"`
}

func (m *HugetlbStats) Reset()                    { *m = HugetlbStats{} }
func (m *HugetlbStats) String() string            { return proto.CompactTextString(m) }
func (*HugetlbStats) ProtoMessage()               {}
func (*HugetlbStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

type CgroupStats struct {
	CpuStats     *CpuStats                `protobuf:"bytes,1,opt,name=cpu_stats" json:"cpu_stats,omitempty"`
	MemoryStats  *MemoryStats             `protobuf:"bytes,2,opt,name=memory_stats" json:"memory_stats,omitempty"`
	BlkioStats   *BlkioStats              `protobuf:"bytes,3,opt,name=blkio_stats" json:"blkio_stats,omitempty"`
	HugetlbStats map[string]*HugetlbStats `protobuf:"bytes,4,rep,name=hugetlb_stats" json:"hugetlb_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *CgroupStats) Reset()                    { *m = CgroupStats{} }
func (m *CgroupStats) String() string            { return proto.CompactTextString(m) }
func (*CgroupStats) ProtoMessage()               {}
func (*CgroupStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *CgroupStats) GetCpuStats() *CpuStats {
	if m != nil {
		return m.CpuStats
	}
	return nil
}

func (m *CgroupStats) GetMemoryStats() *MemoryStats {
	if m != nil {
		return m.MemoryStats
	}
	return nil
}

func (m *CgroupStats) GetBlkioStats() *BlkioStats {
	if m != nil {
		return m.BlkioStats
	}
	return nil
}

func (m *CgroupStats) GetHugetlbStats() map[string]*HugetlbStats {
	if m != nil {
		return m.HugetlbStats
	}
	return nil
}

type Stats struct {
	NetworkStats []*NetworkStats `protobuf:"bytes,1,rep,name=network_stats" json:"network_stats,omitempty"`
	CgroupStats  *CgroupStats    `protobuf:"bytes,2,opt,name=cgroup_stats" json:"cgroup_stats,omitempty"`
	Timestamp    uint64          `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Stats) Reset()                    { *m = Stats{} }
func (m *Stats) String() string            { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()               {}
func (*Stats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *Stats) GetNetworkStats() []*NetworkStats {
	if m != nil {
		return m.NetworkStats
	}
	return nil
}

func (m *Stats) GetCgroupStats() *CgroupStats {
	if m != nil {
		return m.CgroupStats
	}
	return nil
}

type StatsRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *StatsRequest) Reset()                    { *m = StatsRequest{} }
func (m *StatsRequest) String() string            { return proto.CompactTextString(m) }
func (*StatsRequest) ProtoMessage()               {}
func (*StatsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func init() {
	proto.RegisterType((*CreateContainerRequest)(nil), "types.CreateContainerRequest")
	proto.RegisterType((*CreateContainerResponse)(nil), "types.CreateContainerResponse")
	proto.RegisterType((*SignalRequest)(nil), "types.SignalRequest")
	proto.RegisterType((*SignalResponse)(nil), "types.SignalResponse")
	proto.RegisterType((*AddProcessRequest)(nil), "types.AddProcessRequest")
	proto.RegisterType((*User)(nil), "types.User")
	proto.RegisterType((*AddProcessResponse)(nil), "types.AddProcessResponse")
	proto.RegisterType((*CreateCheckpointRequest)(nil), "types.CreateCheckpointRequest")
	proto.RegisterType((*CreateCheckpointResponse)(nil), "types.CreateCheckpointResponse")
	proto.RegisterType((*DeleteCheckpointRequest)(nil), "types.DeleteCheckpointRequest")
	proto.RegisterType((*DeleteCheckpointResponse)(nil), "types.DeleteCheckpointResponse")
	proto.RegisterType((*ListCheckpointRequest)(nil), "types.ListCheckpointRequest")
	proto.RegisterType((*Checkpoint)(nil), "types.Checkpoint")
	proto.RegisterType((*ListCheckpointResponse)(nil), "types.ListCheckpointResponse")
	proto.RegisterType((*StateRequest)(nil), "types.StateRequest")
	proto.RegisterType((*ContainerState)(nil), "types.ContainerState")
	proto.RegisterType((*Process)(nil), "types.Process")
	proto.RegisterType((*Container)(nil), "types.Container")
	proto.RegisterType((*Machine)(nil), "types.Machine")
	proto.RegisterType((*StateResponse)(nil), "types.StateResponse")
	proto.RegisterType((*UpdateContainerRequest)(nil), "types.UpdateContainerRequest")
	proto.RegisterType((*UpdateContainerResponse)(nil), "types.UpdateContainerResponse")
	proto.RegisterType((*EventsRequest)(nil), "types.EventsRequest")
	proto.RegisterType((*Event)(nil), "types.Event")
	proto.RegisterType((*NetworkStats)(nil), "types.NetworkStats")
	proto.RegisterType((*CpuUsage)(nil), "types.CpuUsage")
	proto.RegisterType((*ThrottlingData)(nil), "types.ThrottlingData")
	proto.RegisterType((*CpuStats)(nil), "types.CpuStats")
	proto.RegisterType((*MemoryData)(nil), "types.MemoryData")
	proto.RegisterType((*MemoryStats)(nil), "types.MemoryStats")
	proto.RegisterType((*BlkioStatsEntry)(nil), "types.BlkioStatsEntry")
	proto.RegisterType((*BlkioStats)(nil), "types.BlkioStats")
	proto.RegisterType((*HugetlbStats)(nil), "types.HugetlbStats")
	proto.RegisterType((*CgroupStats)(nil), "types.CgroupStats")
	proto.RegisterType((*Stats)(nil), "types.Stats")
	proto.RegisterType((*StatsRequest)(nil), "types.StatsRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for API service

type APIClient interface {
	CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*CreateContainerResponse, error)
	UpdateContainer(ctx context.Context, in *UpdateContainerRequest, opts ...grpc.CallOption) (*UpdateContainerResponse, error)
	Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error)
	AddProcess(ctx context.Context, in *AddProcessRequest, opts ...grpc.CallOption) (*AddProcessResponse, error)
	CreateCheckpoint(ctx context.Context, in *CreateCheckpointRequest, opts ...grpc.CallOption) (*CreateCheckpointResponse, error)
	DeleteCheckpoint(ctx context.Context, in *DeleteCheckpointRequest, opts ...grpc.CallOption) (*DeleteCheckpointResponse, error)
	ListCheckpoint(ctx context.Context, in *ListCheckpointRequest, opts ...grpc.CallOption) (*ListCheckpointResponse, error)
	State(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error)
	Events(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (API_EventsClient, error)
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (API_GetStatsClient, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*CreateContainerResponse, error) {
	out := new(CreateContainerResponse)
	err := grpc.Invoke(ctx, "/types.API/CreateContainer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateContainer(ctx context.Context, in *UpdateContainerRequest, opts ...grpc.CallOption) (*UpdateContainerResponse, error) {
	out := new(UpdateContainerResponse)
	err := grpc.Invoke(ctx, "/types.API/UpdateContainer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error) {
	out := new(SignalResponse)
	err := grpc.Invoke(ctx, "/types.API/Signal", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) AddProcess(ctx context.Context, in *AddProcessRequest, opts ...grpc.CallOption) (*AddProcessResponse, error) {
	out := new(AddProcessResponse)
	err := grpc.Invoke(ctx, "/types.API/AddProcess", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateCheckpoint(ctx context.Context, in *CreateCheckpointRequest, opts ...grpc.CallOption) (*CreateCheckpointResponse, error) {
	out := new(CreateCheckpointResponse)
	err := grpc.Invoke(ctx, "/types.API/CreateCheckpoint", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DeleteCheckpoint(ctx context.Context, in *DeleteCheckpointRequest, opts ...grpc.CallOption) (*DeleteCheckpointResponse, error) {
	out := new(DeleteCheckpointResponse)
	err := grpc.Invoke(ctx, "/types.API/DeleteCheckpoint", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListCheckpoint(ctx context.Context, in *ListCheckpointRequest, opts ...grpc.CallOption) (*ListCheckpointResponse, error) {
	out := new(ListCheckpointResponse)
	err := grpc.Invoke(ctx, "/types.API/ListCheckpoint", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) State(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error) {
	out := new(StateResponse)
	err := grpc.Invoke(ctx, "/types.API/State", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Events(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (API_EventsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_API_serviceDesc.Streams[0], c.cc, "/types.API/Events", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_EventsClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type aPIEventsClient struct {
	grpc.ClientStream
}

func (x *aPIEventsClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (API_GetStatsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_API_serviceDesc.Streams[1], c.cc, "/types.API/GetStats", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIGetStatsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_GetStatsClient interface {
	Recv() (*Stats, error)
	grpc.ClientStream
}

type aPIGetStatsClient struct {
	grpc.ClientStream
}

func (x *aPIGetStatsClient) Recv() (*Stats, error) {
	m := new(Stats)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for API service

type APIServer interface {
	CreateContainer(context.Context, *CreateContainerRequest) (*CreateContainerResponse, error)
	UpdateContainer(context.Context, *UpdateContainerRequest) (*UpdateContainerResponse, error)
	Signal(context.Context, *SignalRequest) (*SignalResponse, error)
	AddProcess(context.Context, *AddProcessRequest) (*AddProcessResponse, error)
	CreateCheckpoint(context.Context, *CreateCheckpointRequest) (*CreateCheckpointResponse, error)
	DeleteCheckpoint(context.Context, *DeleteCheckpointRequest) (*DeleteCheckpointResponse, error)
	ListCheckpoint(context.Context, *ListCheckpointRequest) (*ListCheckpointResponse, error)
	State(context.Context, *StateRequest) (*StateResponse, error)
	Events(*EventsRequest, API_EventsServer) error
	GetStats(*StatsRequest, API_GetStatsServer) error
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_CreateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CreateContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).CreateContainer(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_UpdateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(UpdateContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).UpdateContainer(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).Signal(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_AddProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(AddProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).AddProcess(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_CreateCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CreateCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).CreateCheckpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_DeleteCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(DeleteCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).DeleteCheckpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_ListCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ListCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).ListCheckpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_State_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).State(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).Events(m, &aPIEventsServer{stream})
}

type API_EventsServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type aPIEventsServer struct {
	grpc.ServerStream
}

func (x *aPIEventsServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _API_GetStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).GetStats(m, &aPIGetStatsServer{stream})
}

type API_GetStatsServer interface {
	Send(*Stats) error
	grpc.ServerStream
}

type aPIGetStatsServer struct {
	grpc.ServerStream
}

func (x *aPIGetStatsServer) Send(m *Stats) error {
	return x.ServerStream.SendMsg(m)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContainer",
			Handler:    _API_CreateContainer_Handler,
		},
		{
			MethodName: "UpdateContainer",
			Handler:    _API_UpdateContainer_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _API_Signal_Handler,
		},
		{
			MethodName: "AddProcess",
			Handler:    _API_AddProcess_Handler,
		},
		{
			MethodName: "CreateCheckpoint",
			Handler:    _API_CreateCheckpoint_Handler,
		},
		{
			MethodName: "DeleteCheckpoint",
			Handler:    _API_DeleteCheckpoint_Handler,
		},
		{
			MethodName: "ListCheckpoint",
			Handler:    _API_ListCheckpoint_Handler,
		},
		{
			MethodName: "State",
			Handler:    _API_State_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Events",
			Handler:       _API_Events_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetStats",
			Handler:       _API_GetStats_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 1433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x57, 0xd9, 0x6e, 0x1c, 0x45,
	0x17, 0xf6, 0xcc, 0xf4, 0x6c, 0x67, 0x16, 0xdb, 0xed, 0xd8, 0x19, 0xcf, 0xff, 0x87, 0x24, 0x4d,
	0x80, 0x08, 0x45, 0x56, 0x70, 0x58, 0x42, 0xb8, 0x80, 0xe0, 0x44, 0x09, 0x28, 0x01, 0x2b, 0xb1,
	0x91, 0xb8, 0x61, 0xd4, 0xee, 0x2e, 0x66, 0x8a, 0xe9, 0x8d, 0xee, 0x6a, 0x2f, 0xaf, 0x80, 0x78,
	0x1e, 0x1e, 0x00, 0x89, 0x7b, 0x9e, 0x83, 0xa7, 0xe0, 0xd4, 0xd2, 0xd5, 0xcb, 0x2c, 0x81, 0x0b,
	0x6e, 0x5a, 0xaa, 0xaa, 0x73, 0xbe, 0xf3, 0x9d, 0xb5, 0xab, 0xa0, 0x6b, 0x47, 0xf4, 0x20, 0x8a,
	0x43, 0x16, 0x9a, 0x4d, 0x76, 0x15, 0x91, 0xc4, 0xfa, 0xb5, 0x06, 0x7b, 0x47, 0x31, 0xb1, 0x19,
	0x39, 0x0a, 0x03, 0x66, 0xd3, 0x80, 0xc4, 0xaf, 0xc8, 0xcf, 0x29, 0x49, 0x98, 0x09, 0x50, 0xa7,
	0xee, 0xa8, 0x76, 0xab, 0x76, 0xb7, 0x6b, 0xe2, 0xe2, 0x2c, 0x0d, 0x5c, 0x8f, 0x1c, 0xdb, 0x6c,
	0x36, 0xaa, 0x8b, 0xbd, 0x01, 0x34, 0x13, 0xe6, 0xd2, 0x60, 0xd4, 0x10, 0xcb, 0x21, 0xb4, 0x70,
	0x19, 0xa6, 0x6c, 0x64, 0x14, 0xd6, 0x24, 0x8e, 0x47, 0x4d, 0xb1, 0xde, 0x84, 0xb6, 0x13, 0x06,
	0x49, 0xe8, 0x91, 0x51, 0x2b, 0xc3, 0x74, 0x66, 0xc4, 0x99, 0x47, 0x21, 0x0d, 0xd8, 0xa8, 0xcd,
	0xf7, 0xac, 0x7d, 0xb8, 0xbe, 0xc0, 0x26, 0x89, 0x50, 0x8d, 0x58, 0x0f, 0x61, 0xf0, 0x9a, 0x4e,
	0x03, 0xdb, 0x5b, 0xc6, 0xaf, 0x07, 0x8d, 0x08, 0x17, 0x9c, 0xd8, 0x40, 0x58, 0x16, 0x92, 0x82,
	0xd9, 0xc0, 0xda, 0x82, 0x61, 0xa6, 0xa9, 0xb0, 0x18, 0x6c, 0x3f, 0x76, 0xdd, 0xe3, 0x38, 0x74,
	0x48, 0x92, 0x2c, 0xc3, 0xdb, 0x82, 0x0e, 0x23, 0xb1, 0x4f, 0x39, 0x08, 0x07, 0xed, 0x98, 0xfb,
	0x60, 0xa4, 0x09, 0x89, 0x05, 0x64, 0xef, 0xb0, 0x77, 0x20, 0xc2, 0x77, 0x70, 0x8a, 0x5b, 0x66,
	0x1f, 0x0c, 0x3b, 0x9e, 0x26, 0xe8, 0x77, 0x43, 0x52, 0x21, 0xc1, 0x39, 0x3a, 0xad, 0x16, 0xce,
	0x85, 0x2b, 0x1d, 0x46, 0x0f, 0x0c, 0x21, 0x8f, 0x9b, 0xa9, 0xb2, 0x34, 0xe0, 0x8b, 0xa9, 0x66,
	0xbe, 0x07, 0x43, 0xdb, 0x75, 0x29, 0xa3, 0x21, 0x1a, 0x7e, 0x46, 0xdd, 0x04, 0xcd, 0x35, 0xd0,
	0x83, 0xdb, 0x60, 0x16, 0xf9, 0x4a, 0x2f, 0x32, 0xa7, 0x05, 0x8e, 0xf5, 0x42, 0x47, 0x4e, 0xc7,
	0x74, 0x99, 0x63, 0xef, 0x94, 0x82, 0x5e, 0x17, 0xce, 0x6c, 0x2b, 0x67, 0x72, 0x4d, 0x6b, 0x0c,
	0xa3, 0x45, 0x34, 0x15, 0xbc, 0x07, 0x70, 0xfd, 0x09, 0xf1, 0xc8, 0x9b, 0x2c, 0x61, 0x54, 0x02,
	0xdb, 0x27, 0xb2, 0x58, 0x38, 0xe0, 0xa2, 0x92, 0x02, 0x7c, 0x1b, 0x76, 0x5f, 0xd0, 0x84, 0xad,
	0x85, 0xb3, 0xbe, 0x07, 0xc8, 0x05, 0x34, 0xb8, 0x36, 0x45, 0x2e, 0x29, 0x53, 0x99, 0xc2, 0xb0,
	0x30, 0x27, 0x12, 0x89, 0xea, 0x98, 0x3b, 0xd0, 0x4b, 0x03, 0x7a, 0xf9, 0x3a, 0x74, 0xe6, 0x84,
	0x25, 0xa2, 0x34, 0x3b, 0xa2, 0x72, 0x67, 0xc4, 0xf3, 0x44, 0x65, 0x76, 0xac, 0x2f, 0x60, 0xaf,
	0x6a, 0x5f, 0x45, 0xf8, 0x5d, 0xe8, 0xe5, 0xd1, 0x4a, 0xd0, 0x5a, 0x63, 0x79, 0xb8, 0x86, 0xd0,
	0x7f, 0xcd, 0x30, 0x5a, 0x8a, 0xb8, 0x75, 0x0b, 0x86, 0xba, 0x80, 0xc5, 0x81, 0xec, 0x06, 0x9b,
	0xa5, 0x89, 0x72, 0x67, 0x0e, 0x6d, 0x95, 0xce, 0x52, 0x1a, 0xff, 0x9b, 0xc2, 0xf3, 0xa0, 0xab,
	0xe9, 0xac, 0xce, 0x51, 0xa5, 0xc9, 0x65, 0x57, 0xdf, 0x86, 0x6e, 0x24, 0x79, 0x12, 0x69, 0xa7,
	0x77, 0x38, 0x54, 0x14, 0x32, 0xfe, 0xb9, 0x6b, 0xa2, 0xd1, 0xb1, 0x3e, 0xda, 0x2f, 0x6d, 0x67,
	0x86, 0xc6, 0xaa, 0xb6, 0x9c, 0x08, 0x85, 0x74, 0x8f, 0xfa, 0xc4, 0x0f, 0xe3, 0x2b, 0x61, 0xc7,
	0xb0, 0xbe, 0xc3, 0xee, 0x96, 0x11, 0x54, 0xa1, 0xbf, 0x83, 0x85, 0x9a, 0x71, 0xce, 0x22, 0xbf,
	0x95, 0x45, 0x5e, 0x3b, 0x73, 0x13, 0xda, 0xbe, 0xb4, 0xa5, 0x6a, 0x39, 0x23, 0xa7, 0x18, 0x58,
	0x4f, 0x60, 0xef, 0x34, 0x72, 0xdf, 0x34, 0xde, 0xf2, 0x89, 0x91, 0x4f, 0x10, 0xe9, 0x52, 0x23,
	0x1b, 0x4b, 0x0b, 0x28, 0xaa, 0x78, 0x37, 0x61, 0xf0, 0xf4, 0x9c, 0x60, 0x75, 0x64, 0xb9, 0xff,
	0xb3, 0x06, 0x4d, 0xb1, 0xc3, 0x3d, 0xe6, 0x64, 0x94, 0x0d, 0x69, 0xaf, 0x9e, 0xcf, 0x46, 0x8d,
	0x3f, 0xa8, 0x44, 0xde, 0x28, 0x8e, 0xb4, 0x66, 0x65, 0xa4, 0xb5, 0xc5, 0x1a, 0xfd, 0x56, 0x69,
	0x19, 0x75, 0x4a, 0x7e, 0x67, 0x49, 0x29, 0x87, 0xaf, 0xbb, 0x22, 0x7c, 0xe5, 0x69, 0x00, 0xab,
	0xa6, 0xc1, 0x6f, 0x35, 0xe8, 0x7f, 0x43, 0xd8, 0x45, 0x18, 0xcf, 0x79, 0x92, 0x92, 0x4a, 0xfb,
	0x61, 0xcd, 0xc6, 0x97, 0x93, 0xb3, 0x2b, 0x46, 0x64, 0x76, 0x0d, 0xee, 0x0f, 0xee, 0x1c, 0xdb,
	0xb2, 0xe9, 0x44, 0x86, 0xcd, 0x6d, 0xe8, 0xbe, 0xba, 0x9c, 0xe0, 0xff, 0x20, 0x8c, 0x65, 0x1f,
	0x0a, 0x31, 0xdc, 0x72, 0xe3, 0x30, 0x8a, 0x88, 0xf4, 0xd4, 0xe0, 0x60, 0x27, 0x19, 0x58, 0x2b,
	0x93, 0xc2, 0x9d, 0x48, 0x81, 0xb5, 0x33, 0xb0, 0x13, 0x0d, 0xd6, 0x29, 0x88, 0x65, 0x60, 0x5d,
	0x51, 0x55, 0x3e, 0x74, 0x8e, 0xa2, 0xf4, 0x34, 0xb1, 0xa7, 0x84, 0x4f, 0x02, 0x16, 0x32, 0xdb,
	0x9b, 0xa4, 0x7c, 0x29, 0xa8, 0x1b, 0xe6, 0x35, 0xe8, 0x47, 0x24, 0xc6, 0xba, 0x54, 0xbb, 0x75,
	0x0c, 0x94, 0x61, 0xfe, 0x0f, 0x76, 0xc4, 0x72, 0x42, 0x83, 0xc9, 0x9c, 0xc4, 0x01, 0xf1, 0xfc,
	0xd0, 0x25, 0xca, 0x8f, 0x7d, 0xd8, 0xd6, 0x87, 0xbc, 0x31, 0xc5, 0x91, 0xf0, 0xc7, 0x3a, 0x81,
	0xe1, 0xc9, 0x0c, 0xff, 0xae, 0xcc, 0xa3, 0xc1, 0xf4, 0x89, 0xcd, 0x6c, 0xfe, 0xd3, 0x43, 0x7c,
	0x1a, 0xba, 0x89, 0x32, 0x88, 0xda, 0x4c, 0x8a, 0x10, 0x77, 0x92, 0x1d, 0xc9, 0xa0, 0xe1, 0xf0,
	0xcf, 0x8f, 0x18, 0xf5, 0x95, 0x41, 0xeb, 0x07, 0xe1, 0x84, 0x0c, 0xbc, 0x05, 0xdd, 0x9c, 0x6c,
	0x4d, 0xe4, 0x6b, 0x33, 0xcb, 0x57, 0xe6, 0xe8, 0x01, 0x6c, 0x32, 0xcd, 0x62, 0x82, 0x55, 0x6b,
	0xab, 0xde, 0xd8, 0x55, 0x92, 0x65, 0x8e, 0xd6, 0xe7, 0x00, 0x2f, 0x45, 0x2b, 0x0a, 0xc6, 0x38,
	0x1b, 0x8b, 0x01, 0xc2, 0x40, 0xfb, 0xf6, 0xa5, 0x8e, 0x0e, 0xdf, 0x42, 0x9f, 0x7e, 0xb4, 0xa9,
	0xe7, 0x60, 0xc5, 0x48, 0x82, 0x7f, 0xd5, 0xa0, 0x27, 0x11, 0x24, 0x49, 0x84, 0x70, 0xb0, 0xfd,
	0x32, 0x88, 0x5b, 0x19, 0x62, 0xf9, 0x6f, 0x53, 0xb0, 0x89, 0x65, 0x98, 0x5c, 0xd8, 0x91, 0xb2,
	0xd2, 0x58, 0x25, 0xf6, 0x1e, 0xf4, 0x65, 0x36, 0x94, 0xa0, 0xb1, 0x4a, 0xf0, 0x1e, 0xbf, 0x99,
	0x20, 0x13, 0x31, 0x0b, 0x7b, 0x87, 0x37, 0x4a, 0x12, 0x82, 0xe3, 0x81, 0xf8, 0x3e, 0x0d, 0x58,
	0x7c, 0x35, 0xbe, 0x07, 0x90, 0xaf, 0x78, 0xdb, 0xcd, 0xc9, 0x95, 0xaa, 0x6c, 0xf4, 0xe4, 0xdc,
	0xf6, 0x52, 0xe5, 0xf9, 0xa3, 0xfa, 0xc3, 0x9a, 0xf5, 0x35, 0x6c, 0x7e, 0xe9, 0xcd, 0x69, 0x58,
	0x50, 0x41, 0x29, 0xdf, 0xfe, 0x29, 0x8c, 0x95, 0xbf, 0x7c, 0x49, 0x03, 0x5c, 0xca, 0x70, 0x61,
	0xdf, 0x87, 0x91, 0x9a, 0xa6, 0x1a, 0x4f, 0xd6, 0xcb, 0xef, 0x0d, 0x80, 0x1c, 0xcc, 0x7c, 0x04,
	0x63, 0x1a, 0x4e, 0xb0, 0xa4, 0xce, 0xa9, 0x43, 0x64, 0x0b, 0x4c, 0x62, 0xe2, 0xa4, 0x71, 0x42,
	0xcf, 0x89, 0x1a, 0x81, 0x7b, 0xca, 0x97, 0x2a, 0x87, 0x8f, 0x60, 0x37, 0xd7, 0x75, 0x0b, 0x6a,
	0xf5, 0xb5, 0x6a, 0x0f, 0x60, 0x07, 0xd5, 0x70, 0x70, 0xa5, 0x25, 0xa5, 0xc6, 0x5a, 0xa5, 0x4f,
	0x61, 0xbf, 0xc0, 0x93, 0x57, 0x6a, 0x41, 0xd5, 0x58, 0xab, 0xfa, 0x31, 0xec, 0xa1, 0xea, 0x85,
	0x4d, 0x59, 0x55, 0xaf, 0xf9, 0x0f, 0x78, 0xfa, 0x24, 0x9e, 0x96, 0x78, 0xb6, 0xd6, 0x2a, 0x7d,
	0x00, 0xdb, 0xa8, 0x54, 0xb1, 0xd3, 0x7e, 0x93, 0x4a, 0x42, 0x1c, 0x86, 0x53, 0xa5, 0xa0, 0xd2,
	0x59, 0xa7, 0x62, 0x3d, 0x86, 0xfe, 0xf3, 0x74, 0x4a, 0x98, 0x77, 0xa6, 0xab, 0xff, 0xdf, 0x36,
	0xd0, 0x2f, 0x75, 0xe8, 0x1d, 0x4d, 0xe3, 0x30, 0x8d, 0x4a, 0x5d, 0x2e, 0x6b, 0x78, 0xa1, 0xcb,
	0xa5, 0xcc, 0x5d, 0xe8, 0xcb, 0x1f, 0xa8, 0x12, 0x93, 0xcd, 0x65, 0x2e, 0x96, 0x3a, 0xbf, 0xc4,
	0x9c, 0x71, 0xce, 0x4a, 0xb0, 0xdc, 0x5e, 0x85, 0xf2, 0xfb, 0x0c, 0x06, 0x33, 0xe9, 0x88, 0x92,
	0x94, 0xa9, 0xbc, 0x93, 0x59, 0xce, 0x09, 0x1e, 0x14, 0x1d, 0x96, 0x4d, 0xf4, 0x1c, 0xb6, 0x17,
	0x36, 0xcb, 0xbd, 0x64, 0x15, 0x7b, 0xa9, 0x77, 0xb8, 0xa3, 0x60, 0x8b, 0x5a, 0xa2, 0xc1, 0x22,
	0x68, 0x4a, 0x3e, 0xef, 0xc3, 0x20, 0x90, 0x3f, 0x1d, 0x1d, 0x89, 0x46, 0x41, 0xb1, 0xf4, 0x43,
	0xc2, 0x68, 0x38, 0x82, 0xdf, 0xd2, 0x68, 0x14, 0x63, 0x8b, 0xf9, 0xe0, 0x15, 0x81, 0x62, 0x7e,
	0xa4, 0xc2, 0x3f, 0x96, 0xb7, 0xb7, 0x65, 0x0f, 0x81, 0xc3, 0x3f, 0x9a, 0xd0, 0x78, 0x7c, 0xfc,
	0x95, 0xf9, 0x0a, 0x36, 0x2b, 0x0f, 0x13, 0x33, 0x1b, 0x2b, 0xcb, 0x9f, 0x4f, 0xe3, 0xb7, 0x56,
	0x1d, 0xab, 0x8b, 0xc3, 0x06, 0xc7, 0xac, 0xdc, 0x2a, 0x34, 0xe6, 0xf2, 0x3b, 0x8b, 0xc6, 0x5c,
	0x75, 0x19, 0xd9, 0x30, 0x3f, 0x81, 0x96, 0x7c, 0xeb, 0x98, 0xd7, 0x94, 0x6c, 0xe9, 0xd1, 0x34,
	0xde, 0xad, 0xec, 0x6a, 0xc5, 0x23, 0x80, 0xfc, 0x89, 0x61, 0x8e, 0x94, 0xd8, 0xc2, 0x2b, 0x69,
	0xbc, 0xbf, 0xe4, 0x44, 0x83, 0x9c, 0xc2, 0x56, 0xf5, 0xd9, 0x60, 0x56, 0xe2, 0x50, 0xbd, 0xe4,
	0x8f, 0x6f, 0xae, 0x3c, 0x2f, 0xc2, 0x56, 0x1f, 0x0f, 0x1a, 0x76, 0xc5, 0x53, 0x44, 0xc3, 0xae,
	0x7c, 0x75, 0x6c, 0x98, 0xdf, 0xc2, 0xb0, 0x7c, 0xef, 0x37, 0xff, 0xaf, 0x94, 0x96, 0x3e, 0x47,
	0xc6, 0x37, 0x56, 0x9c, 0x6a, 0xc0, 0x0f, 0x65, 0xe9, 0xe2, 0x5d, 0x23, 0x8b, 0x72, 0xe1, 0x51,
	0x30, 0xbe, 0x56, 0xde, 0xd4, 0x5a, 0xf7, 0xa1, 0x25, 0x6f, 0x90, 0x3a, 0x65, 0xa5, 0x0b, 0xe5,
	0xb8, 0x5f, 0xdc, 0xb5, 0x36, 0xee, 0xd7, 0x70, 0x4a, 0x75, 0x9e, 0x11, 0x26, 0xeb, 0xb9, 0x68,
	0x6a, 0x41, 0x45, 0x6c, 0x72, 0x95, 0xb3, 0x96, 0x78, 0xf5, 0x3f, 0xf8, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0xa7, 0x4a, 0xd4, 0x7d, 0x02, 0x10, 0x00, 0x00,
}
