#!/bin/sh
set -ex
mkdir -p `pwd`/dist
chmod 777 `pwd`/dist
docker build -t fig .
docker run -u user -v `pwd`/dist:/code/dist --entrypoint pyinstaller fig -F bin/fig
mv dist/fig dist/fig-Linux-x86_64
docker run -u user -v `pwd`/dist:/code/dist --entrypoint dist/fig-Linux-x86_64 fig --version
