#!/bin/bash
set -ex
rm -rf venv
virtualenv venv
venv/bin/pip install -r requirements.txt
venv/bin/pip install -r requirements-dev.txt
venv/bin/pip install .
venv/bin/pyinstaller -F bin/compose
mv dist/compose dist/compose-Darwin-x86_64
dist/compose-Darwin-x86_64 --version
