#!/bin/bash

set -ex

TARGET=dist/docker-compose-Linux-x86_64

mkdir -p `pwd`/dist
chmod 777 `pwd`/dist

pip install -r requirements-build.txt
su -c "pyinstaller -F bin/docker-compose" user
mv dist/docker-compose $TARGET
$TARGET version
