#!/bin/bash
set -ex
rm -rf venv
virtualenv venv
venv/bin/pip install -r requirements.txt
venv/bin/pip install -r requirements-dev.txt
venv/bin/pip install .
venv/bin/pyinstaller -F bin/fig
mv dist/fig dist/fig-Darwin-x86_64
dist/fig-Darwin-x86_64 --version
