#!/bin/bash

set -ex

TARGET=dist/docker-compose-Linux-x86_64
VENV=/code/.tox/py27

mkdir -p `pwd`/dist
chmod 777 `pwd`/dist

$VENV/bin/pip install -q -r requirements-build.txt
./script/write-git-sha
su -c "$VENV/bin/pyinstaller docker-compose.spec" user
mv dist/docker-compose $TARGET
$TARGET version
