#!/bin/bash
# This is a script for running Compose inside a Docker container. It's handy for
# development.
#
# $ ln -s `pwd`/script/dev /usr/local/bin/docker-compose
# $ cd /a/compose/project
# $ docker-compose up
# 

set -e

# Follow symbolic links
if [ -h "$0" ]; then
    DIR=$(readlink "$0")
else
    DIR=$0
fi
DIR="$(dirname "$DIR")"/..

docker build -t docker-compose $DIR
exec docker run -i -t -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`:`pwd` -w `pwd` docker-compose $@
