#!/bin/sh
set -ex
docker build -t compose .
docker run -v /var/run/docker.sock:/var/run/docker.sock --rm --entrypoint flake8 compose compose
docker run -v /var/run/docker.sock:/var/run/docker.sock --rm --entrypoint nosetests compose $@
