#!/bin/bash

# Exit on first error
set -ex

export PYTHON_EGG_CACHE="/tmp/.python-eggs"

TRAVIS_PYTHON_VERSION=$1
source /home/travis/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/activate
env

# Kill background processes on exit
trap 'kill $(jobs -p)' SIGINT SIGTERM EXIT

# Start docker daemon
docker -d -H 0.0.0.0:4243 -H unix:///var/run/docker.sock 2>> /dev/null >> /dev/null &
sleep 2

# $init is set by sekexe
cd $(dirname $init)/.. && nosetests
