#!/bin/bash

set -ex

sudo sh -c "wget -qO- https://get.docker.io/gpg | apt-key add -"
sudo sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
sudo apt-get update
echo exit 101 | sudo tee /usr/sbin/policy-rc.d
sudo chmod +x /usr/sbin/policy-rc.d
sudo apt-get install -qy slirp lxc lxc-docker-0.7.5
git clone git://github.com/jpetazzo/sekexe
python setup.py install
pip install -r requirements-dev.txt

if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then
  pip install unittest2
fi

