#!/usr/bin/env sh

#   Copyright Docker Compose CLI authors

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

set -eu -o pipefail

if ! command -v ltag; then
    >&2 echo "ERROR: ltag not found. Install with:"
    >&2 echo "    go get -u github.com/kunalkushwaha/ltag"
    exit 1
fi

BASEPATH="${1-}"

ltag -t "${BASEPATH}scripts/validate/template" -excludes "validate testdata resolvepath" --check -v