command: docker compose up
short: Create and start containers
long: Create and start containers
usage: docker compose up [SERVICE...]
pname: docker compose
plink: docker_compose.yaml
options:
  - option: abort-on-container-exit
    value_type: bool
    default_value: "false"
    description: |
        Stops all containers if any container was stopped. Incompatible with -d
    deprecated: false
    experimental: false
    experimentalcli: false
    kubernetes: false
    swarm: false
  - option: always-recreate-deps
    value_type: bool
    default_value: "false"
    description: |
        Recreate dependent containers. Incompatible with --no-recreate.
    deprecated: false
    experimental: false
    experimentalcli: false
    kubernetes: false
    swarm: false
  - option: attach-dependencies
    value_type: bool
    default_value: "false"
    description: Attach to dependent containers.
    deprecated: false
    experimental: false
    experimentalcli: false
    kubernetes: false
    swarm: false
  - option: build
    value_type: bool
    default_value: "false"
    description: Build images before starting containers.
    deprecated: false
    experimental: false
    experimentalcli: false
    kubernetes: false
    swarm: false
  - option: detach
    shorthand: d
    value_type: bool
    default_value: "false"
    description: 'Detached mode: Run containers in the background'
    deprecated: false
    experimental: false
    experimentalcli: false
    kubernetes: false
    swarm: false
  - option: environment
    shorthand: e
    value_type: stringArray
    default_value: '[]'
    description: Environment variables
    deprecated: false
    experimental: false
    experimentalcli: false
    kubernetes: false
    swarm: false
  - option: exit-code-from
    value_type: string
    description: |
        Return the exit code of the selected service container. Implies --abort-on-container-exit
    deprecated: false
    experimental: false
    experimentalcli: false
    kubernetes: false
    swarm: false
  - option: force-recreate
    value_type: bool
    default_value: "false"
    description: |
        Recreate containers even if their configuration and image haven't changed.
    deprecated: false
    experimental: false
    experimentalcli: false
    kubernetes: false
    swarm: false
  - option: no-build
    value_type: bool
    default_value: "false"
    description: Don't build an image, even if it's missing.
    deprecated: false
    experimental: false
    experimentalcli: false
    kubernetes: false
    swarm: false
  - option: no-color
    value_type: bool
    default_value: "false"
    description: Produce monochrome output.
    deprecated: false
    experimental: false
    experimentalcli: false
    kubernetes: false
    swarm: false
  - option: no-deps
    value_type: bool
    default_value: "false"
    description: Don't start linked services.
    deprecated: false
    experimental: false
    experimentalcli: false
    kubernetes: false
    swarm: false
  - option: no-log-prefix
    value_type: bool
    default_value: "false"
    description: Don't print prefix in logs.
    deprecated: false
    experimental: false
    experimentalcli: false
    kubernetes: false
    swarm: false
  - option: no-recreate
    value_type: bool
    default_value: "false"
    description: |
        If containers already exist, don't recreate them. Incompatible with --force-recreate.
    deprecated: false
    experimental: false
    experimentalcli: false
    kubernetes: false
    swarm: false
  - option: no-start
    value_type: bool
    default_value: "false"
    description: Don't start the services after creating them.
    deprecated: false
    experimental: false
    experimentalcli: false
    kubernetes: false
    swarm: false
  - option: remove-orphans
    value_type: bool
    default_value: "false"
    description: |
        Remove containers for services not defined in the Compose file.
    deprecated: false
    experimental: false
    experimentalcli: false
    kubernetes: false
    swarm: false
  - option: renew-anon-volumes
    shorthand: V
    value_type: bool
    default_value: "false"
    description: |
        Recreate anonymous volumes instead of retrieving data from the previous containers.
    deprecated: false
    experimental: false
    experimentalcli: false
    kubernetes: false
    swarm: false
  - option: scale
    value_type: stringArray
    default_value: '[]'
    description: |
        Scale SERVICE to NUM instances. Overrides the `scale` setting in the Compose file if present.
    deprecated: false
    experimental: false
    experimentalcli: false
    kubernetes: false
    swarm: false
  - option: timeout
    shorthand: t
    value_type: int
    default_value: "10"
    description: |
        Use this timeout in seconds for container shutdown when attached or when containers are already running.
    deprecated: false
    experimental: false
    experimentalcli: false
    kubernetes: false
    swarm: false
deprecated: false
experimental: false
experimentalcli: false
kubernetes: false
swarm: false

