name: merge

permissions:
  contents: read # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

env:
  REPO_SLUG: "docker/compose-bin"

jobs:
  bin-image-prepare:
    runs-on: ubuntu-24.04
    outputs:
      repo-slug: ${{ env.REPO_SLUG }}
    steps:
      # FIXME: can't use env object in reusable workflow inputs: https://github.com/orgs/community/discussions/26671
      - run: echo "Exposing env vars for reusable workflow"

  bin-image:
    uses: docker/github-builder/.github/workflows/bake.yml@5f637c833aa76bc99372a1dc9a6f8bcd8056fb85 # v1.12.0
    needs:
      - bin-image-prepare
    permissions:
      contents: read # same as global permission
      id-token: write # for signing attestation(s) with GitHub OIDC Token
    with:
      runner: amd64
      target: image-cross
      cache: true
      cache-scope: bin-image
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      sbom: true
      set-meta-labels: true
      meta-images: |
        ${{ needs.bin-image-prepare.outputs.repo-slug }}
      meta-tags: |
        type=ref,event=tag
        type=edge
      meta-bake-target: meta-helper
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ secrets.DOCKERPUBLICBOT_USERNAME }}
          password: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}

  module-image:
    uses: docker/github-builder/.github/workflows/bake.yml@5f637c833aa76bc99372a1dc9a6f8bcd8056fb85 # v1.12.0
    permissions:
      contents: read # same as global permission
      id-token: write # for signing attestation(s) with GitHub OIDC Token
    with:
      runner: amd64
      target: image-module-cross
      cache: true
      cache-scope: module-image
      output: image
      push: ${{ startsWith(github.ref, 'refs/tags/v') }}
      sbom: true
      set-meta-labels: true
      meta-images: |
        docker/compose-desktop-module
      meta-tags: |
        type=ref,event=branch
        type=ref,event=tag
      meta-bake-target: meta-helper
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ secrets.DOCKERPUBLICBOT_USERNAME }}
          password: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}

 