name: merge

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  REPO_SLUG: "docker/compose-bin"

jobs:
  bin-image-prepare:
    runs-on: ubuntu-24.04
    outputs:
      repo-slug: ${{ env.REPO_SLUG }}
    steps:
      # FIXME: can't use env object in reusable workflow inputs: https://github.com/orgs/community/discussions/26671
      - run: echo "Exposing env vars for reusable workflow"

  bin-image:
    uses: docker/github-builder/.github/workflows/bake.yml@70313223e2665c3211b454b3fea6534624e78d64 # v1.4.0
    needs:
      - bin-image-prepare
    permissions:
      contents: read # same as global permission
      id-token: write # for signing attestation(s) with GitHub OIDC Token
    with:
      runner: amd64
      target: image-cross
      cache: true
      cache-scope: bin-image
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      sbom: true
      set-meta-labels: true
      meta-images: |
        ${{ needs.bin-image-prepare.outputs.repo-slug }}
      meta-tags: |
        type=ref,event=tag
        type=edge
      meta-bake-target: meta-helper
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ secrets.DOCKERPUBLICBOT_USERNAME }}
          password: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}

  module-image:
    uses: docker/github-builder/.github/workflows/bake.yml@70313223e2665c3211b454b3fea6534624e78d64 # v1.4.0
    permissions:
      contents: read # same as global permission
      id-token: write # for signing attestation(s) with GitHub OIDC Token
    with:
      runner: amd64
      target: image-module-cross
      cache: true
      cache-scope: module-image
      output: image
      push: ${{ startsWith(github.ref, 'refs/tags/v') }}
      sbom: true
      set-meta-labels: true
      meta-images: |
        docker/compose-desktop-module
      meta-tags: |
        type=ref,event=branch
        type=ref,event=tag
      meta-bake-target: meta-helper
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ secrets.DOCKERPUBLICBOT_USERNAME }}
          password: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}

  desktop-edge-test:
    runs-on: ubuntu-latest
    needs: bin-image
    steps:
      -
        name: Generate Token
        id: generate_token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3
        with:
          app-id: ${{ vars.DOCKERDESKTOP_APP_ID }}
          private-key: ${{ secrets.DOCKERDESKTOP_APP_PRIVATEKEY }}
          owner: docker
          repositories: |
            ${{ secrets.DOCKERDESKTOP_REPO }}
      -
        name: Trigger Docker Desktop e2e with edge version
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'docker',
              repo: '${{ secrets.DOCKERDESKTOP_REPO }}',
              workflow_id: 'compose-edge-integration.yml',
              ref: 'main',
              inputs: {
                "image-tag": "${{ env.REPO_SLUG }}:edge"
              }
            })
