name: 'Close stale issues'
on:
  # schedule:
  #   - cron: '0 0 * * *' # at midnight UTC every day
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'To run in debug mode'
        required: false
        default: "true"
jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          debug-only: ${{ github.event.inputs.debug_enabled }}
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          days-before-issue-stale: 180
          days-before-issue-close: 180
          stale-issue-label: "stale"
          exempt-issue-labels: "kind/feature,kind/enhancement"
          